# 使用的模型及其結果：
*   LogisticRegression ＝ 0.8861
*   GaussianNB ＝ 0.8906
*   SVC ＝ 0.8729
*   RandomForest ＝ 0.8861

# 跑過跑過的組合及其對應結果
*   majority vote ＝ 0.8972
*   weighted vote ＝ 0.8950
*   bagging ＝ 0.8751
*   AdaBoost ＝ 0.8795
*   Stacking ＝ 0.8906


# 最好的結果是
*   Stacking ＝ 0.8906

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data = pd.read_csv('/content/drive/MyDrive/機器學習/bank.csv', delimiter = ";", header = 'infer')
data.y.replace(('yes','no'),(1,0), inplace=True)
data.loan.replace(('yes','no'),(1,0), inplace=True)
data

age            job  marital  education default  balance housing  loan  \
0      30     unemployed  married    primary      no     1787      no     0   
1      33       services  married  secondary      no     4789     yes     1   
2      35     management   single   tertiary      no     1350     yes     0   
3      30     management  married   tertiary      no     1476     yes     1   
4      59    blue-collar  married  secondary      no        0     yes     0   
...   ...            ...      ...        ...     ...      ...     ...   ...   
4516   33       services  married  secondary      no     -333     yes     0   
4517   57  self-employed  married   tertiary     yes    -3313     yes     1   
4518   57     technician  married  secondary      no      295      no     0   
4519   28    blue-collar  married  secondary      no     1137      no     0   
4520   44   entrepreneur   single   tertiary      no     1136     yes     1   

       contact  day month  duration  campaign  pdays  previous poutcome  y  
0     cellular   19   oct        79         1     -1         0  unknown  0  
1     cellular   11   may       220         1    339         4  failure  0  
2     cellular   16   apr       185         1    330         1  failure  0  
3      unknown    3   jun       199         4     -1         0  unknown  0  
4      unknown    5   may       226         1     -1         0  unknown  0  
...        ...  ...   ...       ...       ...    ...       ...      ... ..  
4516  cellular   30   jul       329         5     -1         0  unknown  0  
4517   unknown    9   may       153         1     -1         0  unknown  0  
4518  cellular   19   aug       151        11     -1         0  unknown  0  
4519  cellular    6   feb       129         4    211         3    other  0  
4520  cellular    3   apr       345         2    249         7    other  0  

[4521 rows x 17 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

lb = LabelEncoder()
data.iloc[:,1] = lb.fit_transform(data.iloc[:,1])
data.iloc[:,2] = lb.fit_transform(data.iloc[:,2])
data.iloc[:,3] = lb.fit_transform(data.iloc[:,3])
data.iloc[:,4] = lb.fit_transform(data.iloc[:,4])
data.iloc[:,6] = lb.fit_transform(data.iloc[:,6])
data.iloc[:,8] = lb.fit_transform(data.iloc[:,8])
data.iloc[:,10] = lb.fit_transform(data.iloc[:,10])
data.iloc[:,15] = lb.fit_transform(data.iloc[:,15])
data

age  job  marital  education  default  balance  housing  loan  contact  \
0      30   10        1          0        0     1787        0     0        0   
1      33    7        1          1        0     4789        1     1        0   
2      35    4        2          2        0     1350        1     0        0   
3      30    4        1          2        0     1476        1     1        2   
4      59    1        1          1        0        0        1     0        2   
...   ...  ...      ...        ...      ...      ...      ...   ...      ...   
4516   33    7        1          1        0     -333        1     0        0   
4517   57    6        1          2        1    -3313        1     1        2   
4518   57    9        1          1        0      295        0     0        0   
4519   28    1        1          1        0     1137        0     0        0   
4520   44    2        2          2        0     1136        1     1        0   

      day  month  duration  campaign  pdays  previous  poutcome  y  
0      19     10        79         1     -1         0         3  0  
1      11      8       220         1    339         4         0  0  
2      16      0       185         1    330         1         0  0  
3       3      6       199         4     -1         0         3  0  
4       5      8       226         1     -1         0         3  0  
...   ...    ...       ...       ...    ...       ...       ... ..  
4516   30      5       329         5     -1         0         3  0  
4517    9      8       153         1     -1         0         3  0  
4518   19      1       151        11     -1         0         3  0  
4519    6      3       129         4    211         3         1  0  
4520    3      0       345         2    249         7         1  0  

[4521 rows x 17 columns]

In [57]:
x = np.array(data.iloc[:,0:-1]) #x
y = data.iloc[:,-1] #y
print('x:\n',x)
print('y:\n',y)

ss = StandardScaler()
scaled_data = ss.fit_transform(x.reshape(-1,16))
print(scaled_data, scaled_data.shape)

x:
 [[ 30  10   1 ...  -1   0   3]
 [ 33   7   1 ... 339   4   0]
 [ 35   4   2 ... 330   1   0]
 ...
 [ 57   9   1 ...  -1   0   3]
 [ 28   1   1 ... 211   3   1]
 [ 44   2   2 ... 249   7   1]]
y:
 0       0
1       0
2       0
3       0
4       0
       ..
4516    0
4517    0
4518    0
4519    0
4520    0
Name: y, Length: 4521, dtype: int64
[[-1.05626965  1.71680374 -0.24642938 ... -0.4072183  -0.32041282
   0.44441328]
 [-0.77258281  0.79524562 -0.24642938 ...  2.98904408  2.04173372
  -2.57996071]
 [-0.58345826 -0.12631251  1.42139579 ...  2.89914302  0.27012381
  -2.57996071]
 ...
 [ 1.49691189  1.4096177  -0.24642938 ... -0.4072183  -0.32041282
   0.44441328]
 [-1.24539421 -1.04787063 -0.24642938 ...  1.71045119  1.45119709
  -1.57183605]
 [ 0.26760226 -0.74068459  1.42139579 ...  2.09003345  3.81334363
  -1.57183605]] (4521, 16)


In [58]:
from sklearn.decomposition import PCA

pca = PCA(n_components=6)
x_pca = pca.fit_transform(x)
print('pca')
print(x_pca)
print('pca variance')
print(x_pca.var(axis=0))

pca
[[ 3.64582408e+02 -1.84649224e+02 -4.00096687e+01 -1.14863029e+01
   2.07971238e+00  1.88974083e+00]
 [ 3.36649152e+03 -3.78623322e+01  2.98432342e+02 -8.79515710e+00
  -2.91807451e+00  1.09434222e+00]
 [-7.24588715e+01 -7.76753500e+01  2.90628836e+02 -5.87547372e+00
   2.04223275e+00  2.48174715e+00]
 ...
 [-1.12750827e+03 -1.14727440e+02 -3.99394066e+01  1.60100335e+01
   3.81879423e+00  7.79681714e+00]
 [-2.85420151e+02 -1.34530953e+02  1.72072657e+02 -1.25184517e+01
  -9.01958277e+00 -8.29369891e-01]
 [-2.86703095e+02  8.16497721e+01  2.09084613e+02  3.59971192e+00
  -1.10643139e+01  1.25069483e+00]]
pca variance
[9.05593723e+06 6.74946257e+04 1.00222695e+04 1.11187758e+02
 6.75615936e+01 1.11771415e+01]


In [75]:
x_train, x_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.2, random_state=1000)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.8861878453038674

In [60]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(x_train, y_train)
gnb.score(x_test, y_test)

0.8906077348066298

In [61]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_train, y_train)
svc.score(x_test, y_test)

0.8729281767955801

In [62]:
from sklearn.ensemble import VotingClassifier, RandomForestClassifier

vote = VotingClassifier(estimators=[('lr',lr),('gnb',gnb),('svm',svc)], voting='hard')
vote.fit(x_train, y_train)
vote.score(x_test, y_test)

0.8861878453038674

In [77]:
rfc = RandomForestClassifier(n_estimators=50, random_state=1)
rfc.fit(x_train, y_train)
rfc.score(x_test, y_test)

0.8861878453038674

In [78]:
vote1 = VotingClassifier(estimators=[('lr',lr),('gnb',gnb),('rf',rfc)], voting='soft')
vote1.fit(x_train, y_train)
vote1.score(x_test, y_test)

0.8972375690607735

In [79]:
vote2 = VotingClassifier(estimators=[('lr',lr),('gnb',gnb),('rf',rfc)], voting='soft', weights=[1,1,3])
vote2.fit(x_train, y_train)
vote2.score(x_test, y_test)

0.8950276243093923

In [71]:
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, StackingClassifier

ebc = BaggingClassifier(base_estimator=RandomForestClassifier(), n_estimators=10, max_features=0.8, bootstrap_features=False, max_samples=0.8)
ebc.fit(x_train, y_train)
ebc.score(x_test, y_test)

0.8751381215469614

In [72]:
ada = AdaBoostClassifier(base_estimator=RandomForestClassifier(), n_estimators=100, learning_rate=1.0)
ada.fit(x_train, y_train)
ada.score(x_test, y_test)

0.8795580110497238

In [73]:
stacking = StackingClassifier(estimators=[('lr',lr),('gnb',gnb),('rf',rfc),('svm',svc)], final_estimator=SVC(), cv=30)
stacking.fit(x_train, y_train)
stacking.score(x_test, y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.8906077348066298