比較
*   sklearn：0.8331491712707182
*   tensorflow 的 neural network：0.8685082872928177
*   SVM：0.8729281767955801

SVM效果最好

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [101]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

df = pd.read_csv('/content/drive/MyDrive/機器學習/bank.csv', delimiter=';', header='infer')
df.y.replace(('yes','no'),(1,0), inplace=True)
df.loan.replace(('yes','no'),(1,0), inplace=True)

lb = LabelEncoder()
df.iloc[:,1] = lb.fit_transform(df.iloc[:,1])
df.iloc[:,2] = lb.fit_transform(df.iloc[:,2])
df.iloc[:,3] = lb.fit_transform(df.iloc[:,3])
df.iloc[:,4] = lb.fit_transform(df.iloc[:,4])
df.iloc[:,6] = lb.fit_transform(df.iloc[:,6])
df.iloc[:,8] = lb.fit_transform(df.iloc[:,8])
df.iloc[:,10] = lb.fit_transform(df.iloc[:,10])
df.iloc[:,15] = lb.fit_transform(df.iloc[:,15])
df

age  job  marital  education  default  balance  housing  loan  contact  \
0      30   10        1          0        0     1787        0     0        0   
1      33    7        1          1        0     4789        1     1        0   
2      35    4        2          2        0     1350        1     0        0   
3      30    4        1          2        0     1476        1     1        2   
4      59    1        1          1        0        0        1     0        2   
...   ...  ...      ...        ...      ...      ...      ...   ...      ...   
4516   33    7        1          1        0     -333        1     0        0   
4517   57    6        1          2        1    -3313        1     1        2   
4518   57    9        1          1        0      295        0     0        0   
4519   28    1        1          1        0     1137        0     0        0   
4520   44    2        2          2        0     1136        1     1        0   

      day  month  duration  campaign  pdays  previous  poutcome  y  
0      19     10        79         1     -1         0         3  0  
1      11      8       220         1    339         4         0  0  
2      16      0       185         1    330         1         0  0  
3       3      6       199         4     -1         0         3  0  
4       5      8       226         1     -1         0         3  0  
...   ...    ...       ...       ...    ...       ...       ... ..  
4516   30      5       329         5     -1         0         3  0  
4517    9      8       153         1     -1         0         3  0  
4518   19      1       151        11     -1         0         3  0  
4519    6      3       129         4    211         3         1  0  
4520    3      0       345         2    249         7         1  0  

[4521 rows x 17 columns]

In [102]:
x = np.array(df.iloc[:,0:-1]) #x
y = df.iloc[:,-1] #y
print('x:\n',x)
print('y:\n',y)

ss = StandardScaler()
scaled_data = ss.fit_transform(x.reshape(-1,16))
print(scaled_data, scaled_data.shape)

x:
 [[ 30  10   1 ...  -1   0   3]
 [ 33   7   1 ... 339   4   0]
 [ 35   4   2 ... 330   1   0]
 ...
 [ 57   9   1 ...  -1   0   3]
 [ 28   1   1 ... 211   3   1]
 [ 44   2   2 ... 249   7   1]]
y:
 0       0
1       0
2       0
3       0
4       0
       ..
4516    0
4517    0
4518    0
4519    0
4520    0
Name: y, Length: 4521, dtype: int64
[[-1.05626965  1.71680374 -0.24642938 ... -0.4072183  -0.32041282
   0.44441328]
 [-0.77258281  0.79524562 -0.24642938 ...  2.98904408  2.04173372
  -2.57996071]
 [-0.58345826 -0.12631251  1.42139579 ...  2.89914302  0.27012381
  -2.57996071]
 ...
 [ 1.49691189  1.4096177  -0.24642938 ... -0.4072183  -0.32041282
   0.44441328]
 [-1.24539421 -1.04787063 -0.24642938 ...  1.71045119  1.45119709
  -1.57183605]
 [ 0.26760226 -0.74068459  1.42139579 ...  2.09003345  3.81334363
  -1.57183605]] (4521, 16)


In [103]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1000)

In [104]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_train, y_train)
svc.score(x_test, y_test)

0.8729281767955801

In [7]:
!pip install scikit-multilearn==0.2.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 89 kB 3.6 MB/s 


In [95]:
print(x_train.shape, y_train.shape)

(3616, 16) (3616,)


In [105]:
import tensorflow as tf

y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)
print(y_train, y_train.shape, y_test, y_test.shape)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]] (3616, 2) [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]] (905, 2)


In [106]:
from skmultilearn.problem_transform import BinaryRelevance, ClassifierChain, LabelPowerset
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

classifier = BinaryRelevance(GaussianNB())
classifier.fit(x_train, y_train)
prediction = classifier.predict(x_test)
accuracy_score(y_test, prediction)


0.8331491712707182

In [107]:
CCclassifier = ClassifierChain(GaussianNB())
CCclassifier.fit(x_train, y_train)
CCprediction = CCclassifier.predict(x_test)
accuracy_score(y_test, CCprediction)

0.8331491712707182

In [108]:
LPclassifier = LabelPowerset(GaussianNB())
LPclassifier.fit(x_train, y_train)
LPprediction = LPclassifier.predict(x_test)
accuracy_score(y_test, LPprediction)

0.8331491712707182

In [112]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(20, input_dim=16, kernel_initializer='he_uniform', activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(2, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam')
model.fit(x_train, y_train, epochs=300)
prediction = model.predict(x_test)

Epoch 1/300
113/113 [==============================] - 1s 2ms/step - loss: 10.5820
Epoch 2/300
113/113 [==============================] - 0s 2ms/step - loss: 2.7664
Epoch 3/300
113/113 [==============================] - 0s 2ms/step - loss: 1.7575
Epoch 4/300
113/113 [==============================] - 0s 2ms/step - loss: 1.5654
Epoch 5/300
113/113 [==============================] - 0s 2ms/step - loss: 1.7536
Epoch 6/300
113/113 [==============================] - 0s 2ms/step - loss: 1.4454
Epoch 7/300
113/113 [==============================] - 0s 2ms/step - loss: 1.5928
Epoch 8/300
113/113 [==============================] - 0s 2ms/step - loss: 1.2857
Epoch 9/300
113/113 [==============================] - 0s 2ms/step - loss: 1.3095
Epoch 10/300
113/113 [==============================] - 0s 2ms/step - loss: 1.0364
Epoch 11/300
113/113 [==============================] - 0s 2ms/step - loss: 1.2548
Epoch 12/300
113/113 [==============================] - 0s 2ms/step - loss: 1.8721
Epoch 13/300

In [113]:
prediction = prediction.round()
prediction

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [114]:
accuracy_score(y_test, prediction)

0.8685082872928177